version: '3.8'

services:
    backend:
      build: ./backend
      environment:
        - PORT=27017
        - FOODOHOLIC_DB_URI=
        - DENV=development
        - SECRET=
        - SERVER_EMAIL=
        - SERVER_PASS=
        - GOOGLE_OAUTH_CLIENT_ID=
      restart: unless-stopped
    frontend:
      depends_on:
        - backend
      build: ./frontend
    nginx:
      image: nginx:latest
      container_name: webserver
      restart: unless-stopped
      depends_on:
        - backend
        - frontend
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/local.conf:/etc/nginx/nginx.conf

